spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_jwt?characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
